version: '3.9'
services:
  mysql:
    image: mysql:8.0
    container_name: electricpolegis-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: your_mysql_password
      MYSQL_DATABASE: electric_pole_gis
    ports:
      - "3306:3306"
    volumes:
      - ./database:/docker-entrypoint-initdb.d
      - mysql_data:/var/lib/mysql

  server:
    build: ./server
    container_name: electricpolegis-server
    restart: always
    depends_on:
      - mysql
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=your_mysql_password
      - DB_NAME=electric_pole_gis
      - PORT=5000
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
    command: npm start

volumes:
  mysql_data:
